SELECT *
FROM USERS
JOIN USER_INFORMATION ON USERS.user_informationID = USER_INFORMATION.user_informationID
JOIN PERMISSIONS ON USERS.permissionID = PERMISSIONS.permissionID
WHERE PERMISSIONS.authorityLevel > 0